### ISSUE TITLE
Unable to execute release binaries on 'ubuntu-latest'

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#90] opened 2023-09-04 10:17 UTC
#### 📝 Description

Discovered issues with binary not working on `ubuntu-latest` due to missing ssl package:
    - `./era_test_node: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

#### 🔄 Reproduction Steps

1. In a GitHub Action, set `runs-on: ubuntu-latest`
2. Have a step that runs the following

> echo "Extracting era_test_node binary"
  curl -sL https://github.com/matter-labs/era-test-node/releases/download/v0.1.0/era_test_node-v0.1.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
  chmod +x era_test_node
  echo "Starting node in background"
  ./era_test_node run 2>&1 | tee era_test_node_ouput.log &
  echo "PID=$!" >> $GITHUB_ENV 

4. Notice the error is printed out: `./era_test_node: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

#### 🤔 Expected Behavior

`era_test_node run` should work on `ubuntu-latest` machine with no extra setup required as it's a packaged binary

#### 😯 Current Behavior

Fails with dependency on very specific, old version of libssl package

#### 🖥️ Environment

- This is all running on the `ubuntu-latest` GitHub virtual environment

#### 📋 Additional Context

Also attempted to resolve the issue multiple ways (with no success):
* Tried compiling for `x86_64-unknown-linux-musl` for better cross-compatibility
* Tried to use a specific vendored version of `openssl` to stop using dynamically linked references
* List of all commits for investigation branch: https://github.com/matter-labs/era-test-node/commits/nmv/add-musl-target-to-artifacts
  * Started the investigation with commit `b3ba58745b6372c42396a9c0a72379ca3b4272a8`
* Build with a Docker image that has openssl compiled: https://github.com/clux/muslrust
* ✅ Was able to create a Dockerfile that would run the In-Memory Node, but that doesn't address the underlying issue

**Comment by dutterbutter** [comment] 2023-09-05 12:06
The issue is clear but I have not had success in applying a solution. The issue is the binary is not distributed with `libssl.so.1.0.0` and `libcrypto.so.1.0.0` as depicted below. The other issue is these libraries are obsolete and would need to be installed manually which is not ideal. I am not sure the need for these libs at this time either. 

```
# Run `ldd ./era_test_node` 
 
./era_test_node: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
ubuntu@ip-172-31-6-164:~$ ldd ./era_test_node
	linux-vdso.so.1 (0x00007fff4dda3000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7da5958000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7da593d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7da5933000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7da5910000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7da57bf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7da57b9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7da55c7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7da6e16000)
```

Oddly, when you install `cross` to a fresh environment and then build `era-test-node` you successfully have linked the previously not found libs and it works accordingly so perhaps its CI specific? 
```
    linux-vdso.so.1 (0x00007ffed2685000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7065ecf000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7065e3c000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f7065b66000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7065b4b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7065b41000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7065b1e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70659cd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70659c7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70657d5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f706738d000)
```

**Comment by dutterbutter** [comment] 2023-09-05 16:00
The issue of the binary not being able to find `libssl.so.1.0.0` and `libcrypto.so.1.0.0` can be addressed by providing the following: 

- Add `openssl = { version = "0.10", features = ["vendored"] }` to `Cargo.toml`
- Update `Cross.toml` to 
```
# Cross.toml

[build]
pre-build = [
     "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes apt-utils --no-install-recommends pkg-config cmake libssl-dev:$CROSS_DEB_ARCH libsasl2-dev llvm-dev libclang-6.0-dev clang-6.0"
]
```

After releasing the binaries they are executable and libs are now found:
```
ldd ./era_test_node
	linux-vdso.so.1 (0x00007fff6b797000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70afdb8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70afd9d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f70afd93000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70afd70000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70afc21000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70afc1b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x
```

**Comment by dutterbutter** [comment] 2023-09-05 16:01
@MexicanAce just need to resolve rocksdb headers issue.

**Closed** 2023-09-06 08:19 UTC
Labels: challenging 🏴‍☠️, p0 :white_circle:
