### ISSUE TITLE
Issues when running tests against era-test-node with ethers v6

### ISSUE THREAD

**Issue by mpopovac-txfusion** [matter-labs/era-test-node#217] opened 2023-11-10 10:57 UTC
#### 📝 Description

We are running tests against `era-test-node` and frequently encounter an error with `ethers v6`. The error message received states: `Execution error: Transaction HALT: Account validation error: Reusing the same nonce twice`. This error exhibits non-deterministic behavior, as the test only passes sporadically—one in every ten attempts. Initially, we suspected that the wait() function from `ethers v6` might not reliably await the transaction receipt. However, testing confirmed it does wait until the transaction is processed before proceeding with the test execution. The problem arises when preparing the next transaction; the server appears to return the nonce from the previous transaction. It seems the server does not update the nonce quickly enough in the brief interval between transactions. When we introduced a small timeout before populating the transaction and giving the time for the node to increment the nonce, it worked.

#### 🔄 Reproduction Steps

1. Create a test example with Greeter contract
2. In one test first deploy contract and then call the setGreeting method of the Greeter contract

#### 🤔 Expected Behavior

Transactions are processed sequentially without errors, with era-test-node correctly incrementing the nonce for each new transaction.

#### 😯 Current Behavior

Test only passes sporadically—one in every ten attempts

#### 🖥️ Environment

- **Rust version**: rustc 1.70.0
- **Operating System & Version**: macOS, 13.3.1, apple chip M2

#### 📋 Additional Context

- The tests also ran against a local setup and testnet without issues.
- Tests with ethers v5 were successful. The ethers v5 and v6 implementations differ, with the v6 code being more optimized. In the v5 versions there were a lot of (redundant) steps that, in our opinion, give enough time for era-test-node to increment the nonce for the account

#### 📎 Log Output

```
Execution error: Transaction HALT: Account validation error: Reusing the same nonce twice
```

**Comment by danijelTxFusion** [comment] 2023-12-15 00:42
>The tests also ran against a local setup and testnet without issues.

This issue is also present in [local-setup](https://github.com/matter-labs/local-setup/issues/12).

**Comment by tahos81** [comment] 2024-01-12 11:34
I am having the same problem. Any updates on this ?

**Comment by minhbsq** [comment] 2024-02-01 09:31
I am having the same issues, any updates on this?

**Comment by MexicanAce** [comment] 2024-02-06 10:00
Apologies, I'll take a closer look this week!

**Comment by robsecord** [comment] 2024-02-08 18:42
Gentle bump. Also having this issue.

**Comment by Divide-By-0** [comment] 2024-02-27 09:10
Hey, this issue also seems to be breaking contract deployment scripts for us: https://github.com/matter-labs/hardhat-zksync/issues/714

Any idea when this might be resolved?

**Comment by githubdoramon** [comment] 2024-02-27 13:10
@mpopovac-txfusion can you provide a repo to reproduce the error? We are not being able to reproduce it

**Comment by cheelahim** [comment] 2024-02-27 14:00
@githubdoramon Hmm... I am able to reproduce the issue on the zkSync hardhat solidity starter any time. The worst part is that it's not deterministic, so the tests and other scripts running against era test node are just flaky. Does the following scenario works for you? 
```shell
npx zksync-cli create demo --template hardhat_solidity
cd demo
pnpm test
```
If it passes the first time, try to run a few times in a row.

The only workaround I found is artificially increase the time between the calls for 150-200 ms.
```ts
function sleep(ms: number = 200) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

await contract.someFunction();
await sleep();
await contract.someFunction();
```

**Comment by algtm** [comment] 2024-03-01 05:42
same issues and project testing stuck

**Comment by uF4No** [comment] 2024-03-06 16:21
Looks like this is an issue with ethers v6 caching requests. As the era-test-node processes the transactions so fast, ethers uses the cached value for the nonce instead of retrieving it via `getTransactionCount`.

As a workaround, ethers allows to disable the cache by passing `cacheTimeout: -1` in the Provider option params, so initialising the provider in your tests like this will solve the issue while we decide on the best approach to fix it:

```
const provider = new Provider(url, undefined, {cacheTimeout: -1});
```

**Comment by cheelahim** [comment] 2024-03-08 12:09
@uF4No is there a way to use this workaround with other zkSync hardhat plugins? The `Provider` instantiation is handled by `hardhat-zksync-ethers` plugin which exposes the `Wallet`.

**Comment by kiriyaga-txfusion** [comment] 2024-03-08 13:24
Hello @cheelahim, indeed, there is a workaround for utilizing it with hardhat-zksync-ethers. One of the arguments in helper methods is a wallet object, allowing us to pass a previously created wallet containing a provider configured with {cacheTimeout: -1}. Below is an example from the script demonstrating some sendTransaction call methods and contract deployment:

**Comment by MexicanAce** [comment] 2024-06-28 09:41
After the latest release, we came back to revisit this issue and I'm unable to replicate. As this issue is stemming from the `ethers` v6 NPM package and not this repo, I'll be closing this Issue for now. This could've been resolved by a fix from `ethers`, `zksync-ethers`, and/or the latest `0.1.0-alpha.24` Release of era-test-node.

For awareness, here were the steps we took to attempt to replicate:

Initial setup of example directory:
```bash
nick ~/test $ npx zksync-cli create etn-issue-217
? What type of project do you want to create? Contracts
? Ethereum framework Ethers v6
? Template Hardhat + Solidity
? Private key of the wallet responsible for deploying contracts (optional) 
? Package manager yarn

Setting up template in /Users/nick/test/etn-issue-217...
✔ Cloned template
✔ Environment variables set up
✔ Dependencies installed

🎉 All set up! 🎉

--------------------------

Navigate to your project: cd etn-issue-217

Directory Overview:
  - Contracts: /contracts
  - Deployment Scripts: /deploy
  
Commands:
  - Compile your contracts: yarn compile
  - Deploy your contract: yarn deploy 
    - Tip: You can use the --network option to specify the network to deploy to.

Further Reading:
  - Check out the README file in the project location for more details: etn-issue-217/README.md

--------------------------
nick ~/test $ cd etn-issue-217 
nick ~/test/etn-issue-217 $ yarn test
```

Then I was able to successfully run `yarn test` over 50+ times in a row without failures.

**Closed by MexicanAce** 2024-06-28 09:41 UTC
Labels: bug 🐛, p1 🟠, medium 🚩
