### ISSUE TITLE
Era test node does not implement some hardhat endpoints, in evm namespace

### ISSUE THREAD

**Issue by vbar** [matter-labs/era-test-node#331] opened 2024-08-16 11:38 UTC
#### 📝 Description

Specifically,

`evm_setAutomine`
 - not implemented
 - test node does not have automine mode

`evm_setBlockGasLimit`
 - not implemented
 - tracked in https://github.com/matter-labs/era-test-node/issues/324

`evm_setIntervalMining`
 - not implemented
 - test node does not have automine mode

**Comment by MexicanAce** [comment] 2024-09-18 11:08
This is a duplicate of other GH Issues

**Closed by MexicanAce** 2024-09-18 11:08 UTC
